### ISSUE TITLE
Wrong hashes with big file sizes

### ISSUE THREAD

**Issue by GhostlyDark** [marcrobledo/sfv-checker#1]
The hash values for file sizes equal or higher than 512 MB are wrong. Compared MD5 hashes with WinMD5Free.

Possible workaround: Limit the file size by checking for it in the addFile function.
`if(file.size > 511*1024*1024){alert('File is too large (512 MB max).');return false}`

**Comment by marcrobledo** [comment]
Thanks for warning.
I'll look into it, it can be fixed instead of adding the check.

**Comment by marcrobledo** [comment]
I've fixed it!
I'm also adding a few QoL improvements before pushing the commit.

**Comment by GhostlyDark** [comment]
Still waiting for the fix :)

**Comment by marcrobledo** [comment]
I know it took a 'little' while, but I managed to finish this at last! Need to do a couple of tweaks before the commit though.
